### Testing the create function

POST http://localhost:3000/reports
Content-Type: application/json

{
  "price": 1000,
  "make": "VW", 
  "model": "Golf",
  "year": 2019,
  "lng": 28.10420,
  "lat": -11.71106,
  "mileage": 50000
}

### Approve one report
PATCH http://localhost:3000/reports/approve/1
Content-Type: application/json

{
  "approved": true
}

### Unapprove one report
PATCH http://localhost:3000/reports/approve/1
Content-Type: application/json

{
  "approved": false
}

### Get an estimate for an existing vehicle

GET http://localhost:3000/reports?make=toyota&model=corolla&lng=0&lat=0&mileage=2000&year=1980