### Testing the create function

POST http://localhost:3000/reports
Content-Type: application/json

{
  "price": 15000,
  "make": "Toyota", 
  "model": "Corolla",
  "year": 1982,
  "lng": 45,
  "lat": 46,
  "mileage": 20000
}

### Approve one report
PATCH http://localhost:3000/reports/approve/1
Content-Type: application/json

{
  "approved": true
}

### Unapprove one report
PATCH http://localhost:3000/reports/approve/1
Content-Type: application/json

{
  "approved": false
}

### Get an estimate for an existing vehicle

GET http://localhost:3000/reports?make=Toyota&model=Corolla&lng=44&lat=45&mileage=2000&year=1981